---
title: "p8105_hw5_sc5352"
author: "Chrissy Chen"
date: "2023-11-08"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(tidyverse)
library(dplyr)
library(broom)
library(ggplot2)
```

#### Problem 2

```{r}
# create dataframe to collect file names
file_names = list.files(path = "~/Desktop/P8105/p8105_hw5_sc5352/data/", pattern = "\\.csv$", full.names = TRUE)
data = data.frame(file_name = file_names, stringsAsFactors = FALSE)

# write data from each .csv into the dataframe as a new variable
data = 
  data |>
  mutate(result = map(file_name, read_csv))

# tidy the id from file names to arm + subject ID
tidynames = function(x) {
  x = gsub(".csv$", "", x)
}

# dataframe with id and results columns
tidy_data = 
  data |>
  mutate(id = map(file_name, basename)) |>
  mutate(id = map(id, tidynames)) |>
  select(-file_name) |>
  select(id, result) 

# unlist results columns
unlist_tidydata = 
  tidy_data |>
  unnest_wider(result) |>
  pivot_longer(cols = starts_with("week_"), 
               names_to = "week",
               values_to = "value") |>
  mutate(id = as.character(id))

df = 
  as.data.frame(unlist_tidydata) |>
  na.omit()

ggplot(df, aes(x = week, y = value, group = as.factor(id), color = as.factor(id))) +
  geom_line() +
  labs(x = "Week", y = "Value", title = "Spaghetti Plot") +
  theme_minimal()


```

#### Problem 3
```{r}
set.seed(1)
n = 30
sigma = 5
alpha = 0.05
true_mu_values = 0
num_simulations = 5000

# Function to perform one simulation
sim_one = function(true_mu) {
  # Generate data
  sim_data = tibble(
    x = rnorm(n, mean = true_mu, sd = sigma),
  )
  
  # Perform t-test
   sim_data |> 
      summarize(
        mu_hat = mean(x),
        estimate = tidy(t.test(x, mu = 0))$estimate,
        p_value = tidy(t.test(x, mu = 0))$p.value
        )
}

output = vector("list", 5000)

for (i in 1:5000) {
  output[[i]] = sim_one(30)
}

sim_results = bind_rows(output)

simulation_results =
  map_dfr(true_mu_values, ~ {
  simulations = replicate(num_simulations, sim_one(.x), simplify = "data.frame")
  simulations$true_mu <- .x
  return(simulations)
})


```

